### ISSUE TITLE
add vignette(s) to show how to use the functions

### ISSUE THREAD

**Issue by MattCowgill** [MattCowgill/grattantheme#12]
we already have a number of examples in function documentation (eg. grattan_save(), theme_grattan()). It might encourage use of the package to separate these out into a vignette

**Comment by wfmackey** [comment]
I heart vignettes.
 
I'll have to write some Grattan-y examples for Federica sometime this week and can turn those into vignettes. 

Is there a particular format/etc they require? Or are they just any `pdf`?

**Comment by MattCowgill** [comment]
Awesome, cheers. It should be done as an .rmd file;  see http://kbroman.org/pkg_primer/pages/vignettes.html

**Comment by wfmackey** [comment]
I'll avoid piping/`dplyr` function in the vignette as its not currently in `imports`. This just means plots will start with `ggplot(data, aes(...))` rather than the nicer
```
data %>%
  ggplot(aes(...)) +
  ...
```
i.e. I'll try with all my might not to make this another tutorial on how to use the `tidyverse` and instead a concise note on how to implement `theme_grattan()`.

**Comment by wfmackey** [comment]
First-draft done in #17
