### ISSUE TITLE
Add noteswithsource function

### ISSUE THREAD

**Issue by wfmackey** [MattCowgill/grattantheme#4]
Add `noteswithsource` function to use with 

```
labs(caption = noteswithsource("This is my note", "This is my source"))
```

- Add automatic line break

**Comment by MattCowgill** [comment]
just remembered that the notes & source will only be used with two graph types (blog & fullslide) so we obvs only need to deal with those

**Comment by wfmackey** [comment]
Good thoughting.

**Comment by wfmackey** [comment]
@MattCowgill where should a function like this _live_? In its own .R file? (And then adjust/update it in the `grattan_save.R`?)

**Comment by MattCowgill** [comment]
Yeah I reckon give noteswithsource its own .R file. You've basically already written the code for this I think - you emailed it to me. 

noteswithsource will just update the caption. We'll then add some code to grattan_save that will break the caption over several lines where necessary, depending on the size of the chart

**Comment by MattCowgill** [comment]
Currently, grattan_save("p.png", type = "fullslide"):

- extracts the caption;

- wraps the caption over multiple lines based on the character length of the full caption; then

- adds a line break before the word 'Source', if present.

This could be problematic - it could end up with the 'source' part of the caption having line breaks before they're needed (because the line breaks are inserted based on the total caption length rather than the length of each part).

So I need to change this to:

- break the caption into two pieces `strsplit(stored_caption, "Source")`; 

- wrap each of the two sections onto multiple lines if necessary; 

- add a line break before 'Source'; then

- concatenate the two pieces of the caption and add it back to the chart.





-

**Comment by wfmackey** [comment]
I agree. Have added notes?: and `sources?:`

**Comment by MattCowgill** [comment]
TEAMWORK!
